name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Build
    - name: Build Docker Image
      run: |
        docker build -t cmake-docker-ci .
    
    # Step 3: Run the built container
    - name: Run Docker Container
      run: |
        docker run cmake-docker-ci
